<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-FAP6QC75" failures="8" tests="27" name="acj79_RegistrationFirstName.NegativeSignUpTests" time="262.616" errors="0" timestamp="2021-01-18T12:17:21 PST" skipped="0">
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="12.883">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at reusableUtilities.ReusableMethods.assertEqualStrings(ReusableMethods.java:202)
at pageObjects.SignUpPageObject.validateErrorMessageText(SignUpPageObject.java:55)
at acj79_RegistrationFirstName.NegativeSignUpTests.validateAllErrorMsgForSignUpTest(NegativeSignUpTests.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- validateAllErrorMsgForSignUpTest -->
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="11.117">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at reusableUtilities.ReusableMethods.assertEqualStrings(ReusableMethods.java:202)
at pageObjects.SignUpPageObject.validateErrorMessageText(SignUpPageObject.java:55)
at acj79_RegistrationFirstName.NegativeSignUpTests.validateAllErrorMsgForSignUpTest(NegativeSignUpTests.java:27)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- validateAllErrorMsgForSignUpTest -->
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="8.102"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="8.512"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="8.774"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="11.130">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at reusableUtilities.ReusableMethods.assertEqualStrings(ReusableMethods.java:202)
at pageObjects.SignUpPageObject.validateErrorMessageText(SignUpPageObject.java:55)
at acj79_RegistrationFirstName.NegativeSignUpTests.validateAllErrorMsgForSignUpTest(NegativeSignUpTests.java:27)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- validateAllErrorMsgForSignUpTest -->
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="8.576"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="8.110"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="9.730"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="8.406"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="11.219">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at reusableUtilities.ReusableMethods.assertEqualStrings(ReusableMethods.java:202)
at pageObjects.SignUpPageObject.validateErrorMessageText(SignUpPageObject.java:55)
at acj79_RegistrationFirstName.NegativeSignUpTests.validateAllErrorMsgForSignUpTest(NegativeSignUpTests.java:27)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- validateAllErrorMsgForSignUpTest -->
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="8.439"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="11.898">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at reusableUtilities.ReusableMethods.assertEqualStrings(ReusableMethods.java:202)
at pageObjects.SignUpPageObject.validateErrorMessageText(SignUpPageObject.java:55)
at acj79_RegistrationFirstName.NegativeSignUpTests.validateAllErrorMsgForSignUpTest(NegativeSignUpTests.java:27)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- validateAllErrorMsgForSignUpTest -->
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="12.746"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="11.402">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at reusableUtilities.ReusableMethods.assertEqualStrings(ReusableMethods.java:202)
at pageObjects.SignUpPageObject.validateErrorMessageText(SignUpPageObject.java:55)
at acj79_RegistrationFirstName.NegativeSignUpTests.validateAllErrorMsgForSignUpTest(NegativeSignUpTests.java:27)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- validateAllErrorMsgForSignUpTest -->
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="8.912"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="9.040"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="9.717"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="11.169">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at reusableUtilities.ReusableMethods.assertEqualStrings(ReusableMethods.java:202)
at pageObjects.SignUpPageObject.validateErrorMessageText(SignUpPageObject.java:55)
at acj79_RegistrationFirstName.NegativeSignUpTests.validateAllErrorMsgForSignUpTest(NegativeSignUpTests.java:27)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- validateAllErrorMsgForSignUpTest -->
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="13.293">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at reusableUtilities.ReusableMethods.assertEqualStrings(ReusableMethods.java:202)
at pageObjects.SignUpPageObject.validateErrorMessageText(SignUpPageObject.java:55)
at acj79_RegistrationFirstName.NegativeSignUpTests.validateAllErrorMsgForSignUpTest(NegativeSignUpTests.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- validateAllErrorMsgForSignUpTest -->
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="7.779"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="8.029"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="8.302"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="9.780"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="8.943"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="8.140"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="8.468"/>
  <system-out/>
</testsuite> <!-- acj79_RegistrationFirstName.NegativeSignUpTests -->
