<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-FAP6QC75" failures="8" tests="27" name="acj79_RegistrationFirstName.NegativeSignUpTests" time="273.453" errors="0" timestamp="2021-01-22T21:00:11 PST" skipped="0">
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="11.036">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at reusableUtilities.ReusableMethods.assertEqualStrings(ReusableMethods.java:202)
at pageObjects.SignUpPageObject.validateErrorMessageText(SignUpPageObject.java:55)
at acj79_RegistrationFirstName.NegativeSignUpTests.validateAllErrorMsgForSignUpTest(NegativeSignUpTests.java:27)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- validateAllErrorMsgForSignUpTest -->
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="9.087"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="8.855"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="9.155"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="14.920"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="8.798"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="11.708">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at reusableUtilities.ReusableMethods.assertEqualStrings(ReusableMethods.java:202)
at pageObjects.SignUpPageObject.validateErrorMessageText(SignUpPageObject.java:55)
at acj79_RegistrationFirstName.NegativeSignUpTests.validateAllErrorMsgForSignUpTest(NegativeSignUpTests.java:27)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- validateAllErrorMsgForSignUpTest -->
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="9.332"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="10.357"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="9.065"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="9.344"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="11.924">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at reusableUtilities.ReusableMethods.assertEqualStrings(ReusableMethods.java:202)
at pageObjects.SignUpPageObject.validateErrorMessageText(SignUpPageObject.java:55)
at acj79_RegistrationFirstName.NegativeSignUpTests.validateAllErrorMsgForSignUpTest(NegativeSignUpTests.java:27)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- validateAllErrorMsgForSignUpTest -->
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="9.152"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="11.321">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at reusableUtilities.ReusableMethods.assertEqualStrings(ReusableMethods.java:202)
at pageObjects.SignUpPageObject.validateErrorMessageText(SignUpPageObject.java:55)
at acj79_RegistrationFirstName.NegativeSignUpTests.validateAllErrorMsgForSignUpTest(NegativeSignUpTests.java:27)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- validateAllErrorMsgForSignUpTest -->
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="7.864"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="11.440">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at reusableUtilities.ReusableMethods.assertEqualStrings(ReusableMethods.java:202)
at pageObjects.SignUpPageObject.validateErrorMessageText(SignUpPageObject.java:55)
at acj79_RegistrationFirstName.NegativeSignUpTests.validateAllErrorMsgForSignUpTest(NegativeSignUpTests.java:27)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- validateAllErrorMsgForSignUpTest -->
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="13.067">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at reusableUtilities.ReusableMethods.assertEqualStrings(ReusableMethods.java:202)
at pageObjects.SignUpPageObject.validateErrorMessageText(SignUpPageObject.java:55)
at acj79_RegistrationFirstName.NegativeSignUpTests.validateAllErrorMsgForSignUpTest(NegativeSignUpTests.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- validateAllErrorMsgForSignUpTest -->
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="8.831"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="8.501"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="8.038"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="10.994">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at reusableUtilities.ReusableMethods.assertEqualStrings(ReusableMethods.java:202)
at pageObjects.SignUpPageObject.validateErrorMessageText(SignUpPageObject.java:55)
at acj79_RegistrationFirstName.NegativeSignUpTests.validateAllErrorMsgForSignUpTest(NegativeSignUpTests.java:27)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- validateAllErrorMsgForSignUpTest -->
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="10.791"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="13.394">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at reusableUtilities.ReusableMethods.assertEqualStrings(ReusableMethods.java:202)
at pageObjects.SignUpPageObject.validateErrorMessageText(SignUpPageObject.java:55)
at acj79_RegistrationFirstName.NegativeSignUpTests.validateAllErrorMsgForSignUpTest(NegativeSignUpTests.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- validateAllErrorMsgForSignUpTest -->
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="9.096"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="8.691"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="10.273"/>
  <system-out/>
  <testcase classname="acj79_RegistrationFirstName.NegativeSignUpTests" name="validateAllErrorMsgForSignUpTest" time="8.419"/>
  <system-out/>
</testsuite> <!-- acj79_RegistrationFirstName.NegativeSignUpTests -->
